# Set Up

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
np.random.seed(123)
warnings.filterwarnings('ignore')
%matplotlib inline

In [4]:
competitions = pd.read_csv('Competitions.csv')
competitions.head()

CompID  Country  ... CompStartTime Month CompStartTime Day_of_week
0  ID_WGZ2  ID_HWRH  ...                   6                         5
1  ID_G370      NaN  ...                  12                         7
2  ID_R5HL      NaN  ...                  10                         4
3  ID_Y6XI  ID_ARVG  ...                  11                         4
4  ID_8PEN  ID_I1L9  ...                  11                         4

[5 rows x 17 columns]

In [5]:
competitions.shape

(154, 17)

In [6]:
comppart = pd.read_csv('CompetitionPartipation.csv')
comppart.head()

CompID       UserID  ... CompPartCreated Month CompPartCreated Day_of_week
0  ID_WMUF  ID_UWBBZ9OF  ...                     1                           4
1  ID_MPSN  ID_UWBBZ9OF  ...                     1                           7
2  ID_WMUF  ID_1N5J2PGO  ...                     1                           5
3  ID_7MLO  ID_1N5J2PGO  ...                    10                           5
4  ID_2KEY  ID_1N5J2PGO  ...                     5                           4

[5 rows x 7 columns]

In [7]:
comppart.shape

(48565, 7)

In [8]:
users = pd.read_csv('Users.csv')
users.head()

UserID  FeatureX  ... UserDate Month  UserDate Day_of_week
0  ID_N5LTBAPU         0  ...              4                     4
1  ID_CLSFQB0S         0  ...              5                     4
2  ID_RE6T58Y4         0  ...             12                     3
3  ID_XJQQRJV3         0  ...              9                     2
4  ID_1JHU6A8S         0  ...             10                     1

[5 rows x 8 columns]

In [9]:
users.shape

(22407, 8)

In [10]:
submission = pd.read_csv('Submissions.csv')
submission.head()

UserID  FeatureG  ... SubDate Month  SubDate Day_of_week
0  ID_8JP75F20         1  ...             3                    2
1  ID_8JP75F20         1  ...             3                    2
2  ID_8JP75F20         1  ...             3                    4
3  ID_8JP75F20         1  ...             3                    2
4  ID_8JP75F20         1  ...             3                    4

[5 rows x 6 columns]

In [11]:
submission.shape

(375763, 6)

In [12]:
discussion = pd.read_csv('Discussions.csv')
discussion.head()

FeatureF  DiscDate Year  ...     DiscID       UserID
0         1              3  ...  ID_Z77ETQ  ID_F2757IAI
1         0              3  ...  ID_E47JKY  ID_F2757IAI
2         1              3  ...  ID_CB4Y0N  ID_F2757IAI
3         0              3  ...  ID_BNIHCF  ID_F2757IAI
4         1              3  ...  ID_MLPYCO  ID_F2757IAI

[5 rows x 6 columns]

In [13]:
discussion.shape

(6211, 6)

In [14]:
comment = pd.read_csv('Comments.csv')
comment.head()

UserID  CommentDate Year  CommentDate Month  CommentDate Day_of_week
0  ID_MVIB05DL                 3                  1                        7
1  ID_MVIB05DL                 3                  1                        7
2  ID_KBRFRAR9                 3                  1                        7
3  ID_UDS6FRR8                 3                  1                        7
4  ID_UDS6FRR8                 3                  1                        7

In [15]:
comment.shape

(11751, 4)

In [16]:
tr= pd.read_csv('Train.csv')
tr.head()

User_ID  month  year  CompPart  Comment  Sub  Disc  Target
0  ID_XI7BAR4Y      8     3         0        0    0     0       0
1  ID_XI7BAR4Y      8     2         0        0    0     0       0
2  ID_XI7BAR4Y      9     2         0        0    0     0       0
3  ID_XI7BAR4Y      9     3         0        0    0     0       0
4  ID_XI7BAR4Y     10     3         0        0    0     0       0

In [17]:
tr.shape

(259832, 8)

In [18]:
vdef = pd.read_csv('VariableDefinitions.csv')
vdef

VariableName                                                                                                   VariableDefinition
0                                                            Train                                                                                                                  NaN
1                                                           UserID                                                               This is the unique ID of the user who made the comment
2                                                         CompPart                                               Value 1 if Participated in any competition in the given month and year
3                                                          Comment                                                  Value 1 if Participated in any comments in the given month and year
4                                                              Sub                                                  Value 1 if Submitted to any competition in the given month and year
..                                                             ...                                                                                                                  ...
67                                                  UserDate Month  The month of the year the user signed up. Months are in chronological order but January is not neccesarily month 1.
68                                            UserDate Day_of_week      The day of the week the user signed up on. Days are in chronological order but Monday is not neccesarily day 1.
69                                                             NaN                                                                                                                  NaN
70                                                             NaN                                                                                                                  NaN
71  The variables have been masked consistently across all tables.                                                                                                                  NaN

[72 rows x 2 columns]

In [19]:
ts = pd.read_csv('Test.csv')
ts.head()

User_ID  month  year
0  ID_H1ELY25E      1     4
1  ID_H1ELY25E      2     4
2  ID_H1ELY25E      3     4
3  ID_463Q2BCO      1     4
4  ID_463Q2BCO      2     4

In [20]:
ts.shape

(65223, 3)

In [21]:
ss = pd.read_csv('SampleSubmission.csv')
ss.head()

UserMonthYear  Target
0  ID_000VV0KM_1_4     NaN
1  ID_000VV0KM_2_4     NaN
2  ID_000VV0KM_3_4     NaN
3  ID_003OCIYO_1_4     NaN
4  ID_003OCIYO_2_4     NaN

In [22]:
ss.shape

(65223, 2)

# Data Understanding

**COMPETITIONS**

In [23]:
competitions.dtypes

CompID                        object
Country                       object
FeatureA                      object
FeatureB                      object
FeatureC                     float64
Kind                           int64
Points Reward                  int64
FeatureD                       int64
SecretCode                     int64
SubmissionLimitPerDay        float64
FeatureE                      object
CompEndTime Year              object
CompEndTime Month            float64
CompEndTime Day_of_week      float64
CompStartTime Year             int64
CompStartTime Month            int64
CompStartTime Day_of_week      int64
dtype: object

In [24]:
competitions.isna().sum()

CompID                        0
Country                      23
FeatureA                      0
FeatureB                      0
FeatureC                     17
Kind                          0
Points Reward                 0
FeatureD                      0
SecretCode                    0
SubmissionLimitPerDay         4
FeatureE                      0
CompEndTime Year              0
CompEndTime Month            20
CompEndTime Day_of_week      20
CompStartTime Year            0
CompStartTime Month           0
CompStartTime Day_of_week     0
dtype: int64

In [25]:
competitions.duplicated().any()

False

In [26]:
#unique elements in our data:
cols = competitions.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', competitions[col].nunique())
  print(competitions[col].unique())
  print()

COLUMN: CompID
Number of unique variables: 154
['ID_WGZ2' 'ID_G370' 'ID_R5HL' 'ID_Y6XI' 'ID_8PEN' 'ID_F23U' 'ID_GOXL'
 'ID_88GO' 'ID_HTKR' 'ID_ABBZ' 'ID_ASHZ' 'ID_LXXE' 'ID_I52W' 'ID_TKJJ'
 'ID_57TX' 'ID_ZBPQ' 'ID_SNXY' 'ID_GTIV' 'ID_P8IG' 'ID_GQCR' 'ID_BQO2'
 'ID_4FPW' 'ID_664W' 'ID_GCU7' 'ID_5B6Q' 'ID_JIF0' 'ID_LMFN' 'ID_G31W'
 'ID_HJ9S' 'ID_RSV3' 'ID_R4NQ' 'ID_SW6X' 'ID_5HIG' 'ID_1FDX' 'ID_JQS3'
 'ID_92AG' 'ID_3HST' 'ID_BT9Z' 'ID_18R6' 'ID_3HLK' 'ID_UIC7' 'ID_CKLY'
 'ID_4DT4' 'ID_JYR6' 'ID_0HHR' 'ID_TLNA' 'ID_YXS6' 'ID_AWEI' 'ID_50Y5'
 'ID_F53H' 'ID_QXRY' 'ID_TL9O' 'ID_AXVN' 'ID_VNW7' 'ID_VS6D' 'ID_H4L8'
 'ID_TIK1' 'ID_3G07' 'ID_V5M1' 'ID_HZ45' 'ID_OBP1' 'ID_WIA6' 'ID_QCN2'
 'ID_LQ4P' 'ID_GI2A' 'ID_F0B5' 'ID_VDSL' 'ID_Y20Y' 'ID_T638' 'ID_S3FU'
 'ID_O4PY' 'ID_VNN1' 'ID_EZD0' 'ID_UWCU' 'ID_3XEN' 'ID_3JA7' 'ID_58T1'
 'ID_ZSZR' 'ID_1E58' 'ID_IUTP' 'ID_92VT' 'ID_DJJ7' 'ID_1INW' 'ID_IV8G'
 'ID_1CBJ' 'ID_SIY6' 'ID_D0T1' 'ID_XWMG' 'ID_QQTZ' 'ID_YZ4I' 'ID_81JW'
 'ID_SV8O' 'ID_DKSX' 'ID_7MLO'

**COMPETITION** **PARTICIPATION**

In [27]:
comppart.dtypes

CompID                         object
UserID                         object
PublicRank                     object
Successful Submission Count    object
CompPartCreated Year            int64
CompPartCreated Month           int64
CompPartCreated Day_of_week     int64
dtype: object

In [28]:
comppart.isna().sum()

CompID                             0
UserID                             0
PublicRank                     34598
Successful Submission Count    32426
CompPartCreated Year               0
CompPartCreated Month              0
CompPartCreated Day_of_week        0
dtype: int64

In [29]:
comppart.duplicated().any()

True

In [47]:
comppart.duplicated().sum()

8

In [30]:
#unique elements in our data:
cols = comppart.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', comppart[col].nunique())
  print(comppart[col].unique())
  print()

COLUMN: CompID
Number of unique variables: 137
['ID_WMUF' 'ID_MPSN' 'ID_7MLO' 'ID_2KEY' 'ID_50DK' 'ID_AWEI' 'ID_ON5E'
 'ID_QQTZ' 'ID_F53H' 'ID_FBDX' 'ID_D42Y' 'ID_4DT4' 'ID_H4L8' 'ID_UIC7'
 'ID_3JA7' 'ID_1CBJ' 'ID_LQ4P' 'ID_U1HE' 'ID_R5HL' 'ID_HJ9S' 'ID_VNN1'
 'ID_1INW' 'ID_AXVN' 'ID_8PEN' 'ID_G7A4' 'ID_UBMS' 'ID_XWMG' 'ID_ZSZR'
 'ID_XYJZ' 'ID_GCU7' 'ID_JYR6' 'ID_IV8G' 'ID_WGZ2' 'ID_81JW' 'ID_8WX8'
 'ID_SV8O' 'ID_TLNA' 'ID_09D8' 'ID_VS6D' 'ID_IAYS' 'ID_GI2A' 'ID_GTIV'
 'ID_O4PY' 'ID_SAZ4' 'ID_G370' 'ID_Y6XI' 'ID_GQCR' 'ID_FAR8' 'ID_1E58'
 'ID_QXRY' 'ID_LMFN' 'ID_J66M' 'ID_TYYF' 'ID_ABBZ' 'ID_G7MQ' 'ID_P8IG'
 'ID_KG1B' 'ID_N932' 'ID_F7X4' 'ID_DKSX' 'ID_VAQG' 'ID_T638' 'ID_QY5J'
 'ID_V5M1' 'ID_ZBPQ' 'ID_GOXL' 'ID_SW6X' 'ID_88GO' 'ID_E1LI' 'ID_F0B5'
 'ID_3G07' 'ID_G31W' 'ID_664W' 'ID_3HST' 'ID_QCN2' 'ID_D0T1' 'ID_HZ45'
 'ID_VK18' 'ID_HTKR' 'ID_OBP1' 'ID_RSV3' 'ID_VDSL' 'ID_0HHR' 'ID_UWCU'
 'ID_CEI6' 'ID_0G47' 'ID_R4NQ' 'ID_JIF0' 'ID_I5BX' 'ID_WIA6' 'ID_IUTP'
 'ID_YZ4I' 'ID_C59X' 'ID_SNXY'

**USERS**

In [31]:
users.dtypes

UserID                  object
FeatureX                 int64
Country                 object
FeatureY                 int64
Points                  object
UserDate Year            int64
UserDate Month           int64
UserDate Day_of_week     int64
dtype: object

In [32]:
users.isna().sum()

UserID                  0
FeatureX                0
Country                 0
FeatureY                0
Points                  0
UserDate Year           0
UserDate Month          0
UserDate Day_of_week    0
dtype: int64

In [33]:
users.duplicated().any()

False

In [34]:
#unique elements in our data:
cols = users.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', users[col].nunique())
  print(users[col].unique())
  print()

COLUMN: UserID
Number of unique variables: 22407
['ID_N5LTBAPU' 'ID_CLSFQB0S' 'ID_RE6T58Y4' ... 'ID_XAQGPGAZ' 'ID_1AO7PVP2'
 'ID_3ZXJIREU']

COLUMN: FeatureX
Number of unique variables: 2
[0 1]

COLUMN: Country
Number of unique variables: 148
['ID_DMRM' 'ID_Q02' 'ID_Z8BI' 'ID_5OWN' 'ID_PLTE' 'ID_NVM2' 'ID_GU74'
 'ID_0NU5' 'ID_60OO' 'ID_G4IW' 'ID_ZXLV' 'ID_HIXK' 'ID_CXB1' 'ID_Y8RA'
 'ID_FC41' 'ID_2XYB' 'ID_ACV0' 'ID_ARVG' 'ID_OZ6F' 'ID_EKIH' 'ID_66JY'
 'ID_2GBE' 'ID_111K' 'ID_BAUQ' 'ID_RAZW' 'ID_HWRH' 'ID_QUOO' 'ID_QA2H'
 'ID_CZ6Z' 'ID_EYN3' 'ID_6RGX' 'ID_TZX5' 'ID_5U59' 'ID_N98T' 'ID_38MP'
 'ID_INB3' 'ID_1ATT' 'ID_6923' 'ID_U4GT' 'ID_Y4KK' 'ID_ABPY' 'ID_6P8R'
 'ID_XX6B' 'ID_YIPK' 'ID_HIN5' 'ID_K86O' 'ID_WVNE' 'ID_OS8P' 'ID_A5LV'
 'ID_QF70' 'ID_VLOE' 'ID_CKI7' 'ID_X354' 'ID_U1SY' 'ID_EUWR' 'ID_53QI'
 'ID_2PMY' 'ID_CPF9' 'ID_MFQY' 'ID_XPPQ' 'ID_U6OW' 'ID_SS6G' 'ID_M1LR'
 'ID_5DCZ' 'ID_JBUL' 'ID_BN9Z' 'ID_AQ8U' 'ID_SJ36' 'ID_FBM5' 'ID_FJL5'
 'ID_Y9V4' 'ID_FF7V' 'ID_WY95' 'ID_74H2' 'ID_MT5

**SUBMISSIONS**

In [35]:
submission.dtypes

UserID                 object
FeatureG                int64
CompID                 object
SubDate Year            int64
SubDate Month           int64
SubDate Day_of_week     int64
dtype: object

In [36]:
submission.isna().sum()

UserID                 0
FeatureG               0
CompID                 0
SubDate Year           0
SubDate Month          0
SubDate Day_of_week    0
dtype: int64

In [37]:
submission.duplicated().any()

True

In [49]:
submission.duplicated().sum()

311767

In [38]:
#unique elements in our data:
cols = submission.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', submission[col].nunique())
  print(submission[col].unique())
  print()

COLUMN: UserID
Number of unique variables: 7265
['ID_8JP75F20' 'ID_CB7ZH4MJ' 'ID_QUU4R5LF' ... 'ID_XT1B3WN7' 'ID_CX5N3Q88'
 'ID_J6MM98N2']

COLUMN: FeatureG
Number of unique variables: 3
[1 0 3]

COLUMN: CompID
Number of unique variables: 136
['ID_GFDE' 'ID_MPSN' 'ID_MICX' 'ID_C59X' 'ID_GCU7' 'ID_GQCR' 'ID_W0EJ'
 'ID_Z5QP' 'ID_8PEN' 'ID_AWEI' 'ID_HJ9S' 'ID_G7A4' 'ID_ABBZ' 'ID_F7X4'
 'ID_VDSL' 'ID_D42Y' 'ID_3JA7' 'ID_AXVN' 'ID_H4L8' 'ID_7MLO' 'ID_T638'
 'ID_U1HE' 'ID_50DK' 'ID_IAYS' 'ID_V5M1' 'ID_8WX8' 'ID_3HST' 'ID_664W'
 'ID_SW6X' 'ID_E1LI' 'ID_OBP1' 'ID_R5HL' 'ID_SV8O' 'ID_VNN1' 'ID_SNXY'
 'ID_FBDX' 'ID_TLNA' 'ID_JYR6' 'ID_9E5U' 'ID_TIK1' 'ID_VK18' 'ID_P8IG'
 'ID_F53H' 'ID_WL75' 'ID_S3FU' 'ID_UBMS' 'ID_4DT4' 'ID_Y20Y' 'ID_Y6XI'
 'ID_ZSZR' 'ID_J66M' 'ID_GTIV' 'ID_QCN2' 'ID_GI2A' 'ID_N932' 'ID_DKSX'
 'ID_0HHR' 'ID_2KEY' 'ID_WGZ2' 'ID_LMFN' 'ID_88GO' 'ID_VS6D' 'ID_1E58'
 'ID_GOXL' 'ID_HTKR' 'ID_3G07' 'ID_XWMG' 'ID_BT9Z' 'ID_JAOW' 'ID_QXRY'
 'ID_PWC6' 'ID_KG1B' 'ID_1INW' 'ID_IV8G' 'ID_1C

**DISCUSSIONS**

In [50]:
discussion.dtypes

FeatureF                 int64
DiscDate Year            int64
DiscDate Month           int64
DiscDate Day_of_week     int64
DiscID                  object
UserID                  object
dtype: object

In [51]:
discussion.isna().sum()

FeatureF                0
DiscDate Year           0
DiscDate Month          0
DiscDate Day_of_week    0
DiscID                  0
UserID                  0
dtype: int64

In [52]:
discussion.duplicated().any()

False

In [53]:
#unique elements in our data:
cols = discussion.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', discussion[col].nunique())
  print(discussion[col].unique())
  print()

COLUMN: FeatureF
Number of unique variables: 2
[1 0]

COLUMN: DiscDate Year
Number of unique variables: 3
[3 2 1]

COLUMN: DiscDate Month
Number of unique variables: 12
[10 12  1  9  5  4  6 11  2  3  7  8]

COLUMN: DiscDate Day_of_week
Number of unique variables: 7
[1 3 7 2 6 4 5]

COLUMN: DiscID
Number of unique variables: 6211
['ID_Z77ETQ' 'ID_E47JKY' 'ID_CB4Y0N' ... 'ID_IMGAT1' 'ID_W3CY00'
 'ID_GT26RF']

COLUMN: UserID
Number of unique variables: 2653
['ID_F2757IAI' 'ID_JQJGZA7V' 'ID_OO9NRDUE' ... 'ID_UC2B2DBT' 'ID_VVUWHX7W'
 'ID_A9FRILEL']



**COMMENTS**

In [43]:
comment.dtypes

UserID                     object
CommentDate Year            int64
CommentDate Month           int64
CommentDate Day_of_week     int64
dtype: object

In [44]:
comment.isna().sum()

UserID                     0
CommentDate Year           0
CommentDate Month          0
CommentDate Day_of_week    0
dtype: int64

In [45]:
comment.duplicated().any()

True

In [46]:
comment.duplicated().sum()

5237

In [47]:
#unique elements in our data:
cols = comment.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', comment[col].nunique())
  print(comment[col].unique())
  print()

COLUMN: UserID
Number of unique variables: 2055
['ID_MVIB05DL' 'ID_KBRFRAR9' 'ID_UDS6FRR8' ... 'ID_ZVE0W61X' 'ID_0B9SK73T'
 'ID_2IKJFHYK']

COLUMN: CommentDate Year
Number of unique variables: 3
[3 2 1]

COLUMN: CommentDate Month
Number of unique variables: 12
[ 1  2 11 12  4  7  9  8 10  3  6  5]

COLUMN: CommentDate Day_of_week
Number of unique variables: 7
[7 2 6 5 4 3 1]



**TRAIN**

In [ ]:
tr.dtypes

User_ID     object
month        int64
year         int64
CompPart     int64
Comment      int64
Sub          int64
Disc         int64
Target       int64
dtype: object

In [ ]:
ts.dtypes

User_ID    object
month       int64
year        int64
dtype: object

In [ ]:
tr.isna().sum()

User_ID     0
month       0
year        0
CompPart    0
Comment     0
Sub         0
Disc        0
Target      0
dtype: int64

In [ ]:
ts.isna().sum()

User_ID    0
month      0
year       0
dtype: int64

In [ ]:
#unique elements in our data:
cols = tr.columns.to_list()

for col in cols:
  print('COLUMN:', col)
  print('Number of unique variables:', tr[col].nunique())
  print(tr[col].unique())
  print()

COLUMN: User_ID
Number of unique variables: 20218
['ID_XI7BAR4Y' 'ID_TY9GL3X7' 'ID_ZOYZ41L5' ... 'ID_8IKU22O5' 'ID_NHWCR1IY'
 'ID_XMD7EIYV']

COLUMN: month
Number of unique variables: 12
[ 8  9 10 11 12  1  2  3  4  5  6  7]

COLUMN: year
Number of unique variables: 3
[3 2 1]

COLUMN: CompPart
Number of unique variables: 2
[0 1]

COLUMN: Comment
Number of unique variables: 2
[0 1]

COLUMN: Sub
Number of unique variables: 2
[0 1]

COLUMN: Disc
Number of unique variables: 2
[0 1]

COLUMN: Target
Number of unique variables: 2
[0 1]



In [ ]:
#checking for duplicates
tr.duplicated().any()

False

In [ ]:
ts.duplicated().any()

False